# Compiler and linker configurations
CXX := g++
CXXFLAGS := -O3 -MMD -MP -std=c++17
LDFLAGS := -Lsrc -Wl,-rpath,src

# Directory configurations
SRC_DIR := src
BUILD_DIR := build
# DATASET_DIR := dataset

# Source and object files
SOURCES := $(wildcard $(SRC_DIR)/*.cpp)
OBJECTS := $(patsubst $(SRC_DIR)/%.cpp,$(BUILD_DIR)/%.o,$(SOURCES))
DEPENDS := $(OBJECTS:.o=.d)  # Dependency files for each object file
EXECUTABLE := $(BUILD_DIR)/run

# Default target
all: $(EXECUTABLE)

# Linking the executable
$(EXECUTABLE): $(OBJECTS)
	$(CXX) $(OBJECTS) -o $@ $(LDFLAGS) $(LDLIBS)

# Compiling source files into objects
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp
	@mkdir -p $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) -I$(SRC_DIR) -c $< -o $@

# Include the dependency files generated by -MMD flag
-include $(DEPENDS)

# Clean up
clean:
	rm -f $(BUILD_DIR)/*.o $(BUILD_DIR)/*.d $(EXECUTABLE)

# Phony targets
.PHONY: all clean